//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holy_Bible.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Holy_Bible.Cultures.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警示.
        /// </summary>
        internal static string Global_ShowMessage_Alert {
            get {
                return ResourceManager.GetString("Global_ShowMessage_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string Global_ShowMessage_Info {
            get {
                return ResourceManager.GetString("Global_ShowMessage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在.
        /// </summary>
        internal static string MainPage_Panorama_About {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聖經是有史以來最暢銷的書。加入的人誰讀聖書和大家分享這手頭的應用始終是您最喜愛的社交網絡福音百萬美元。.
        /// </summary>
        internal static string MainPage_Panorama_About_App_Resume {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About_App_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聖經.
        /// </summary>
        internal static string MainPage_Panorama_About_App_Title {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本1.1.
        /// </summary>
        internal static string MainPage_Panorama_About_App_Version {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About_App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數據庫在中國.
        /// </summary>
        internal static string MainPage_Panorama_About_Book_Language_Database {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About_Book_Language_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中國協和版.
        /// </summary>
        internal static string MainPage_Panorama_About_Book_Translation {
            get {
                return ResourceManager.GetString("MainPage_Panorama_About_Book_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認刪除的喜愛？.
        /// </summary>
        internal static string MainPage_Panorama_Bookmark_Delete_Confirmation {
            get {
                return ResourceManager.GetString("MainPage_Panorama_Bookmark_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的最愛.
        /// </summary>
        internal static string MainPage_Panorama_Bookmarks {
            get {
                return ResourceManager.GetString("MainPage_Panorama_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖書.
        /// </summary>
        internal static string MainPage_Panorama_Books {
            get {
                return ResourceManager.GetString("MainPage_Panorama_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        internal static string MainPage_Panorama_Search {
            get {
                return ResourceManager.GetString("MainPage_Panorama_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研究.
        /// </summary>
        internal static string MainPage_Panorama_Search_Button {
            get {
                return ResourceManager.GetString("MainPage_Panorama_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聖經.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最愛.
        /// </summary>
        internal static string ReadPage_ApplicationBar_Bookmark {
            get {
                return ResourceManager.GetString("ReadPage_ApplicationBar_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一.
        /// </summary>
        internal static string ReadPage_ApplicationBar_Next {
            get {
                return ResourceManager.GetString("ReadPage_ApplicationBar_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以前的.
        /// </summary>
        internal static string ReadPage_ApplicationBar_Previous {
            get {
                return ResourceManager.GetString("ReadPage_ApplicationBar_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 傳送.
        /// </summary>
        internal static string ReadPage_ApplicationBar_Share {
            get {
                return ResourceManager.GetString("ReadPage_ApplicationBar_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指數.
        /// </summary>
        internal static string ReadPage_Panorama_Index {
            get {
                return ResourceManager.GetString("ReadPage_Panorama_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所選的書籤已經存在於數據庫中。.
        /// </summary>
        internal static string ReadPage_Panorama_Reader_Bookmark_Add_Exists {
            get {
                return ResourceManager.GetString("ReadPage_Panorama_Reader_Bookmark_Add_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書籤添加成功！.
        /// </summary>
        internal static string ReadPage_Panorama_Reader_Bookmark_Add_Success {
            get {
                return ResourceManager.GetString("ReadPage_Panorama_Reader_Bookmark_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇至少一首詩。.
        /// </summary>
        internal static string ReadPage_Panorama_Reader_Bookmark_Select_Alert {
            get {
                return ResourceManager.GetString("ReadPage_Panorama_Reader_Bookmark_Select_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請只選擇一首詩。.
        /// </summary>
        internal static string ReadPage_Panorama_Reader_Share_Alert {
            get {
                return ResourceManager.GetString("ReadPage_Panorama_Reader_Share_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發送到.
        /// </summary>
        internal static string SharePage_Title {
            get {
                return ResourceManager.GetString("SharePage_Title", resourceCulture);
            }
        }
    }
}
